### ISSUE TITLE
Maxima 5.34.1 and 5.35.1 Debian Jessie: 

### ISSUE THREAD

**Issue by stumari** [maths/quiz_stack#1]
Hi,
I am getting the following errors after running healthcheck script both in case when using Maxima 5.34.1 and 5.35.1 on Debian Jessie. Most likely the error has been caused by moodle-qtype_stack because it at version 2014112600.

healthcheck  output is attached bellow:
Display-style equation [works]
Inline-style equation [works]

Maxima configuration file
Trying to automatically write the Maxima configuration file.
Maxima configuration file
/* ***********************************************************************/
/* This file is automatically generated at installation time.            */
/* The purpose is to transfer configuration settings to Maxima.          */
/* Hence, you should not edit this file.  Edit your configuration.       */
/* This file is regularly overwritten, so your changes will be lost.     */
/* ***********************************************************************/

/* File generated on January 7, 2015, 9:01 pm */

/* Add the location to Maxima's search path */
file_search_maxima:append( [sconcat("/var/www/html/moodle/question/type/stack/stack/maxima/###.{mac,mc}")] , file_search_maxima)$
file_search_lisp:append( [sconcat("/var/www/html/moodle/question/type/stack/stack/maxima/###.{lisp}")] , file_search_lisp)$
file_search_maxima:append( [sconcat("/var/www/moodledata/stack/logs/###.{mac,mc}")] , file_search_maxima)$
file_search_lisp:append( [sconcat("/var/www/moodledata/stack/logs/###.{lisp}")] , file_search_lisp)$

STACK_SETUP(ex):=block(
    MAXIMA_VERSION_NUM:35.1,
    TMP_IMAGE_DIR:"/var/www/moodledata/stack/tmp/",
    IMAGE_DIR:"/var/www/moodledata/stack/plots/",
    PLOT_TERMINAL:"png",
    PLOT_TERM_OPT:"large transparent size 450,300",
    DEL_CMD:"rm",
    GNUPLOT_CMD:"gnuplot",
    MAXIMA_VERSION:"5.35.1",
    URL_BASE:"!ploturl!",
    true)$
/* Load the main libraries */
load("stackmaxima.mac")$

Maxima version
The version of the STACK-Maxima libraries being used (So old the version is unknown!) does not match what is expected (2014112600) by this version of the STACK question type. It is not really clear how that happened. You will need to debug this problem yourself. Start by clearing the CAS cache.

Graph plotting [does not work]

Errors
CAS failed to return any evaluated expressions. Please check your connection with the CAS.

FAILED	CAS returned some data as expected, but there were errors.
FAILED	The version of the STACK-Maxima libraries being used (So old the version is unknown!) does not match what is expected (2014112600) by this version of the STACK question type. It is not really clear how that happened. You will need to debug this problem yourself. Start by clearing the CAS cache.
CAS results are being cached in the database.

**Comment by sangwinc** [comment]
Ok, I had some problems with Maxima 5.35.1 on Windows, but this was related
to plots. The maths was fine. I'll try to compile this on Debian myself.
It would help if you could send me the actual output (try CAS debugging on
in the menu).  It might be nothing to do with the Maxima version here....

Chris

**Comment by tonyjbutler** [comment]
Hi Chris,

We're having the same issue with version 2015090900 of qtype_stack and Maxima 5.34.1 on Debian Jessie.

The STACK healthcheck output, including debug info, is pasted below:

Maxima configuration file
Trying to automatically write the Maxima configuration file.


/* ***********************************************************************/
/* This file is automatically generated at installation time.            */
/* The purpose is to transfer configuration settings to Maxima.          */
/* Hence, you should not edit this file.  Edit your configuration.       */
/* This file is regularly overwritten, so your changes will be lost.     */
/* ***********************************************************************/

/* File generated on January 21, 2016, 12:27 pm */

/* Add the location to Maxima's search path */
file_search_maxima:append( [sconcat("/srv/www/dev.mle.lancs.ac.uk/29/question/type/stack/stack/maxima/###.{mac,mc}")] , file_search_maxima)$
file_search_lisp:append( [sconcat("/srv/www/dev.mle.lancs.ac.uk/29/question/type/stack/stack/maxima/###.{lisp}")] , file_search_lisp)$
file_search_maxima:append( [sconcat("/srv/data/dev/29/stack/logs/###.{mac,mc}")] , file_search_maxima)$
file_search_lisp:append( [sconcat("/srv/data/dev/29/stack/logs/###.{lisp}")] , file_search_lisp)$

STACK_SETUP(ex):=block(
    MAXIMA_VERSION_NUM:34.1,
    MAXIMA_PLATFORM:"unix",
    maxima_tempdir:"/srv/data/dev/29/stack/tmp/",
    IMAGE_DIR:"/srv/data/dev/29/stack/plots/",
    PLOT_TERMINAL:"png",
    PLOT_TERM_OPT:"large transparent size 450,300",
    DEL_CMD:"rm",
    GNUPLOT_CMD:"gnuplot",
    MAXIMA_VERSION:"5.34.1",
    URL_BASE:"!ploturl!",
    true)$
/* Load the main libraries */
load("stackmaxima.mac")$

Uncached CAS call
This section always sends a genuine call to the CAS, regardless of the current cache settings. This is needed to ensure the connection to the CAS is really currently working.


( ! ) Notice: Undefined index: key in /srv/www/dev.mle.lancs.ac.uk/29/question/type/stack/stack/cas/connectorhelper.class.php on line 306
Call Stack
#	Time	Memory	Function	Location
1	0.0020	335552	{main}( )	../healthcheck.php:0
2	0.6431	14089024	stack_connection_helper::stackmaxima_genuine_connect( )	../healthcheck.php:121

( ! ) Notice: Undefined index: key in /srv/www/dev.mle.lancs.ac.uk/29/question/type/stack/stack/cas/connectorhelper.class.php on line 310
Call Stack
#	Time	Memory	Function	Location
1	0.0020	335552	{main}( )	../healthcheck.php:0
2	0.6431	14089024	stack_connection_helper::stackmaxima_genuine_connect( )	../healthcheck.php:121

( ! ) Notice: Undefined index: key in /srv/www/dev.mle.lancs.ac.uk/29/question/type/stack/stack/cas/connectorhelper.class.php on line 314
Call Stack
#	Time	Memory	Function	Location
1	0.0020	335552	{main}( )	../healthcheck.php:0
2	0.6431	14089024	stack_connection_helper::stackmaxima_genuine_connect( )	../healthcheck.php:121

( ! ) Notice: Undefined index: key in /srv/www/dev.mle.lancs.ac.uk/29/question/type/stack/stack/cas/connectorhelper.class.php on line 314
Call Stack
#	Time	Memory	Function	Location
1	0.0020	335552	{main}( )	../healthcheck.php:0
2	0.6431	14089024	stack_connection_helper::stackmaxima_genuine_connect( )	../healthcheck.php:121
CAS returned some data as expected, but there were errors.

Debug info
Context used
Platform: unix
Maxima shell command: maxima
Maxima initial command: load("/srv/data/dev/29/stack/maximalocal.mac");


Maxima timeout: 5
Maxima command
cab:block([],print("[TimeStamp= [ 0 ], Locals= [ 0=[ error= ["), cte("CASresult",errcatch(diff(x^n,x))), print("1=[ error= ["), cte("STACKversion",errcatch(stackmaximaversion)), print("2=[ error= ["), cte("MAXIMAversion",errcatch(MAXIMA_VERSION)), print("3=[ error= ["), cte("CAStime",errcatch(CAStime:"2016-01-21 12:27:53")), print("] ]"), return(true));
Timings
Start: 1453379273.1441, End: 1453379273.7521, Taken = 0.60807394981384
CAS result
Maxima 5.34.1 http://maxima.sourceforge.net
using Lisp GNU Common Lisp (GCL) GCL 2.6.12 (a.k.a. GCL)
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) 
file_search1: eval_string not found in file_search_maxima,file_search_lisp.
#0: stack_reset(rand_seed=1000)(stackmaxima.mac line 51)
 -- an error. To debug this try: debugmode(true);
(%i1) 
[TimeStamp= [ 0 ], Locals= [ 0=[ error= [ 
1=[ error= [ 
2=[ error= [ 
3=[ error= [ 
] ] 
(%o1) true
(%i2) 
Unpacked result as
Array
(
    [0] => Array
        (
            [error] => 1=[ error= [ 2=[ error= [ 3=[ error= [ ] ] (%o1) true(%
        )

)
Trying to connect to the CAS
We are trying to evaluate the following CAS text:

The derivative of @ x^4/(1+x^4) @ is \[ \frac{d}{dx} \frac{x^4}{1+x^4} = @ diff(x^4/(1+x^4),x) @. \]
The derivative of x^4/(1+x^4) is \frac{d}{dx} \frac{x^4}{1+x^4} = diff(x^4/(1+x^4),x).
Errors
CAS failed to return any evaluated expressions. Please check your connection with the CAS.
Debug info
Maxima command
cab:block([ RANDOM_SEED, OPT_NoFloats, sqrtdispflag, simp, assume_pos, lmxchar, caschat0, caschat1], stack_randseed(0), make_multsgn("dot"), make_complexJ("i"), make_arccos("cos-1"), OPT_NoFloats:true, sqrtdispflag:true, simp:true, assume_pos:false, lmxchar:"[", print("[TimeStamp= [ 0 ], Locals= [ ") , print("-1=[ error= ["), cte("__stackmaximaversion",errcatch(__stackmaximaversion:stackmaximaversion)) , print("0=[ error= ["), cte("caschat0",errcatch(caschat0:x^4/(1+x^4))) , print("1=[ error= ["), cte("caschat1",errcatch(caschat1:diff(x^4/(1+x^4),x))) , print("] ]") , return(true) ); 
 
Unpacked result found in the DB cache
Array
(
    [-1] => Array
        (
            [error] => 0=[ error= [ 1=[ error= [ ] ] (%o1) t
        )

)
Maxima version

( ! ) Notice: Undefined index: key in /srv/www/dev.mle.lancs.ac.uk/29/question/type/stack/stack/cas/connectorhelper.class.php on line 227
Call Stack
#	Time	Memory	Function	Location
1	0.0020	335552	{main}( )	../healthcheck.php:0
2	1.3150	14173640	stack_connection_helper::stackmaxima_version_healthcheck( )	../healthcheck.php:151
The version of the STACK-Maxima libraries being used (So old the version is unknown!) does not match what is expected (2015090900) by this version of the STACK question type. It is not really clear how that happened. You will need to debug this problem yourself. Start by clearing the CAS cache.

Graph plotting
There should be two different plots. If two identical plots are seen then this is an error in naming the plot files. If no errors are returned, but a plot is not displayed then one of the following may help. (i) check read permissions on the two temporary directories. (ii) change the options used by GNUPlot to create the plot. Currently there is no web interface to these options.

Two example plots below.  @plot([x^4/(1+x^4),diff(x^4/(1+x^4),x)],[x,-3,3])@ @plot([sin(x),x,x^2,x^3],[x,-3,3],[y,-3,3])@
Two example plots below.  plot([x^4/(1+x^4),diff(x^4/(1+x^4),x)],[x,-3,3])plot([sin(x),x,x^2,x^3],[x,-3,3],[y,-3,3])
Errors
CAS failed to return any evaluated expressions. Please check your connection with the CAS.
Debug info
Maxima command
cab:block([ RANDOM_SEED, OPT_NoFloats, sqrtdispflag, simp, assume_pos, lmxchar, caschat0, caschat1], stack_randseed(0), make_multsgn("dot"), make_complexJ("i"), make_arccos("cos-1"), OPT_NoFloats:true, sqrtdispflag:true, simp:true, assume_pos:false, lmxchar:"[", print("[TimeStamp= [ 0 ], Locals= [ ") , print("-1=[ error= ["), cte("__stackmaximaversion",errcatch(__stackmaximaversion:stackmaximaversion)) , print("0=[ error= ["), cte("caschat0",errcatch(caschat0:plot([x^4/(1+x^4),diff(x^4/(1+x^4),x)],[x,-3,3]))) , print("1=[ error= ["), cte("caschat1",errcatch(caschat1:plot([sin(x),x,x^2,x^3],[x,-3,3],[y,-3,3]))) , print("] ]") , return(true) ); 
 
Unpacked result found in the DB cache
Array
(
    [-1] => Array
        (
            [error] => 0=[ error= [ 1=[ error= [ ] ] (%o1) t
        )

)
CAS result caching
CAS results are being cached in the database.

The cache currently contains 3 entries.

Clear the cache
FAILED	CAS returned some data as expected, but there were errors.
FAILED	The version of the STACK-Maxima libraries being used (So old the version is unknown!) does not match what is expected (2015090900) by this version of the STACK question type. It is not really clear how that happened. You will need to debug this problem yourself. Start by clearing the CAS cache.
CAS results are being cached in the database.

**Comment by tonyjbutler** [comment]
By the way, the same version of qtype_stack works fine with Maxima 5.27.0 on Debian Wheezy.

Cheers,
Tony

**Comment by sangwinc** [comment]
Tony, 

I think this issue has been reported here:
https://github.com/maths/moodle-qtype_stack/issues/149
Some versions of Maxima on some platforms are not complete.  This is rather frustrating for everyone, but issue #149 has been resolved.
If this doesn't work, please re-open the issue and I will look again.

Chris

**Comment by tonyjbutler** [comment]
Thanks Chris. I tried everything mentioned in that issue, but in the end the only thing that fixed it was compiling Maxima from source with SBCL, as you recommended in the discussion at https://moodle.org/mod/forum/discuss.php?d=313727.

**Comment by kabalin** [comment]
Hi, we managed to make packaged version of Maxima in Debian Jessie work (Maxima 5.34.1 and GCL). For the platform type "Linux" it does not work though, but if optimised version is created using [documentation](https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/CAS/Optimising_Maxima.md#gcl), then it works smooth and there are no errors or warnings in health-check. The important bit is to have "platform" set to "Linux" in STACK configuration in Moodle, set "Maxima command" to empty value and run health-check once, before building an optimised binary using the commands in the document.

**Comment by sangwinc** [comment]
Thanks for posting this.  Are you up and running or do you need more help here?
Chris

**Comment by kabalin** [comment]
@sangwinc No, it just was a comment that it works for Jessie if optimised version is in use, someone may find it useful.

**Comment by sangwinc** [comment]
Thanks.  Please do keep in touch and let me know how you get on with STACK with your students....
